-- Fix missing columns in medicine table
USE bht;
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS dosage_form VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS product_code VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS usage_dosage VARCHAR(255);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS contraindication VARCHAR(255);

USE wx;
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS dosage_form VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS product_code VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS usage_dosage VARCHAR(255);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS contraindication VARCHAR(255);

USE rzt_db;
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS dosage_form VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS product_code VARCHAR(50);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS usage_dosage VARCHAR(255);
ALTER TABLE medicine ADD COLUMN IF NOT EXISTS contraindication VARCHAR(255);

