CREATE TABLE IF NOT EXISTS boss (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO boss (username, password)
SELECT 'boss', '123456' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM boss WHERE username = 'boss');

